# Assignment 10 (Syed Sajid Ali)

#### Q.1 Find record if Sales greater than 500 and Quantity greater than 5?

In [2]:
# Step 1- Import pandas library
import pandas as pd

In [3]:
# Step-2 import csv in Data Frame
df = pd.read_csv('retail supermarket1.csv')
df

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.2480,3,0.20,4.1028
9990,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.9600,2,0.00,15.6332
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.5760,2,0.20,19.3932
9992,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.6000,4,0.00,13.3200
9993,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.1600,2,0.00,72.9480

In [4]:
# Step 3: records filter 
result = df[(df['Sales'] > 500) & (df['Quantity'] > 5)]

In [5]:
# Step 4: Output display 
result

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
7,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.152,6,0.2,90.7152
10,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,1706.184,9,0.2,85.3092
16,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,665.880,6,0.0,13.3176
27,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Furniture,Bookcases,3083.430,7,0.5,-1665.0522
35,First Class,Corporate,United States,Richardson,Texas,75080,Central,Technology,Phones,1097.544,7,0.2,123.4737
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9879,Standard Class,Consumer,United States,New York City,New York,10035,East,Furniture,Chairs,573.174,7,0.1,63.6860
9925,First Class,Corporate,United States,New York City,New York,10035,East,Office Supplies,Binders,1087.936,8,0.2,353.5792
9942,Standard Class,Consumer,United States,Anaheim,California,92804,West,Office Supplies,Storage,998.820,9,0.0,29.9646
9947,Second Class,Corporate,United States,Indianapolis,Indiana,46203,Central,Furniture,Chairs,1925.880,6,0.0,539.2464
9948,Second Class,Corporate,United States,Indianapolis,Indiana,46203,Central,Office Supplies,Appliances,2405.200,8,0.0,793.7160

#### Q.2 Find records if Discount is more than 0.5 (50%) or Profit is negative.

In [6]:
# Step 1: Discount > 0.5 or Profit < 0 
result_q2 = df[(df['Discount'] > 0.5) | (df['Profit'] < 0)]

# Step 2: Output display
result_q2

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
14,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,68.8100,5,0.80,-123.8580
15,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,2.5440,3,0.80,-3.8160
23,Second Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Furniture,Chairs,71.3720,2,0.30,-1.0196
27,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Furniture,Bookcases,3083.4300,7,0.50,-1665.0522
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9920,Standard Class,Corporate,United States,Bryan,Texas,77803,Central,Office Supplies,Binders,22.3860,7,0.80,-35.8176
9921,Standard Class,Home Office,United States,Akron,Ohio,44312,East,Office Supplies,Binders,5.7420,3,0.70,-4.5936
9931,Standard Class,Consumer,United States,San Bernardino,California,92404,West,Furniture,Bookcases,683.3320,4,0.15,-40.1960
9937,Second Class,Corporate,United States,Los Angeles,California,90049,West,Furniture,Tables,71.0880,2,0.20,-1.7772
9962,First Class,Home Office,United States,Houston,Texas,77041,Central,Furniture,Bookcases,383.4656,4,0.32,-67.6704

#### Q.3 Display Ship Mode and Profit columns if region is East using loc

In [7]:
# Step-1: "Filter the East region using loc and display only two columns."
result_q3 = df.loc[df['Region'] == 'East', ['Ship Mode', 'Profit']]

# Step-2 Output display
result_q3

           Ship Mode     Profit
23      Second Class    -1.0196
27    Standard Class -1665.0522
28    Standard Class    -7.0532
29    Standard Class    15.5250
30    Standard Class     1.1016
...              ...        ...
9968  Standard Class   331.1910
9969  Standard Class     6.5975
9981     First Class     5.3690
9984  Standard Class    15.1200
9985  Standard Class    16.1240

[2848 rows x 2 columns]

#### Q.4 How many records belong to the "Corporate" segment and the "Central" region?

In [9]:
# Step 1: Corporate data filter 
filtered_data = df[(df['Segment'] == 'Corporate') & (df['Region'] == 'Central')]

# Step 2: Print Counting Total Records
print(f"Total Records Found: {len(filtered_data)}")

# Step 3: Display Data Filter
filtered_data

Total Records Found: 673

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
21,Standard Class,Corporate,United States,Fremont,Nebraska,68025,Central,Office Supplies,Art,19.460,7,0.0,5.0596
22,Standard Class,Corporate,United States,Fremont,Nebraska,68025,Central,Office Supplies,Appliances,60.340,7,0.0,15.6884
35,First Class,Corporate,United States,Richardson,Texas,75080,Central,Technology,Phones,1097.544,7,0.2,123.4737
36,First Class,Corporate,United States,Richardson,Texas,75080,Central,Furniture,Furnishings,190.920,5,0.6,-147.9630
41,Standard Class,Corporate,United States,Naperville,Illinois,60540,Central,Technology,Phones,147.168,4,0.2,16.5564
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9947,Second Class,Corporate,United States,Indianapolis,Indiana,46203,Central,Furniture,Chairs,1925.880,6,0.0,539.2464
9948,Second Class,Corporate,United States,Indianapolis,Indiana,46203,Central,Office Supplies,Appliances,2405.200,8,0.0,793.7160
9949,Second Class,Corporate,United States,Indianapolis,Indiana,46203,Central,Technology,Accessories,83.970,3,0.0,15.9543
9950,Second Class,Corporate,United States,Indianapolis,Indiana,46203,Central,Technology,Accessories,39.890,1,0.0,14.7593
9951,Second Class,Corporate,United States,Indianapolis,Indiana,46203,Central,Office Supplies,Binders,17.380,2,0.0,8.6900

#### Q.5  Find all orders in the "Furniture" category but not in "Chairs" sub-category.

In [10]:
# Step 1: Furniture category filter & Chairs sub-category exclude 
furniture_Chairs = df[(df['Category'] == 'Furniture') & (df['Sub-Category'] != 'Chairs')]

# Step 2: Filtered table display 
furniture_Chairs

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
5,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,48.8600,7,0.00,14.1694
10,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,1706.1840,9,0.20,85.3092
24,Standard Class,Consumer,United States,Orem,Utah,84057,West,Furniture,Tables,1044.6300,3,0.00,240.2649
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9962,First Class,Home Office,United States,Houston,Texas,77041,Central,Furniture,Bookcases,383.4656,4,0.32,-67.6704
9964,Second Class,Corporate,United States,Newark,Delaware,19711,East,Furniture,Furnishings,13.4000,1,0.00,6.4320
9980,Second Class,Consumer,United States,Lafayette,Louisiana,70506,South,Furniture,Tables,85.9800,1,0.00,22.3548
9989,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.2480,3,0.20,4.1028
9990,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.9600,2,0.00,15.6332

#### Q.6 Which orders have discount (>0.3) and still earned profit (>0)?

In [8]:
# Step 1: Discount & profit filter karein
discount_profit = df[(df['Discount'] > 0.3) & (df['Profit'] > 0)]

# Step 2: Display function use karein
display(discount_profit)

# Step 3: Total Counting
print(f"total_discount_profit = {len(discount_profit)} records")

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
343,Second Class,Corporate,United States,Philadelphia,Pennsylvania,19140,East,Technology,Phones,71.928,12,0.4,8.3916
614,Second Class,Consumer,United States,Grove City,Ohio,43123,East,Technology,Phones,119.940,10,0.4,15.9920
986,Standard Class,Home Office,United States,Pasadena,Texas,77506,Central,Technology,Machines,336.510,3,0.4,44.8680
1233,First Class,Corporate,United States,Cincinnati,Ohio,45231,East,Technology,Copiers,839.988,2,0.4,69.9990
1679,Standard Class,Corporate,United States,Philadelphia,Pennsylvania,19134,East,Technology,Phones,32.382,3,0.4,4.3176
1912,Second Class,Corporate,United States,Houston,Texas,77041,Central,Technology,Machines,597.132,3,0.4,49.7610
1986,First Class,Consumer,United States,Columbus,Ohio,43229,East,Technology,Copiers,1439.976,4,0.4,191.9968
2125,Standard Class,Home Office,United States,Philadelphia,Pennsylvania,19143,East,Technology,Phones,62.958,7,0.4,9.4437
2135,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19134,East,Technology,Phones,94.920,4,0.4,15.8200
2728,First Class,Consumer,United States,Toledo,Ohio,43615,East,Technology,Phones,629.958,7,0.4,94.4937
3781,Second Class,Consumer,United States,Philadelphia,Pennsylvania,19120,East,Technology,Phones,269.982,3,0.4,40.4973
4003,Standard Class,Consumer,United States,San Antonio,Texas,78207,Central,Technology,Machines,287.910,3,0.4,33.5895
4491,Second Class,Consumer,United States,Columbus,Ohio,43229,East,Technology,Copiers,659.988,2,0.4,109.9980
4812,Second Class,Consumer,United States,Philadelphia,Pennsylvania,19134,East,Technology,Copiers,1199.976,4,0.4,179.9964
5384,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19143,East,Technology,Phones,358.200,3,0.4,41.7900
5385,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19143,East,Technology,Phones,545.916,14,0.4,72.7888
6425,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19120,East,Technology,Copiers,8399.976,4,0.4,1119.9968
6951,Standard Class,Corporate,United States,Dallas,Texas,75217,Central,Technology,Machines,479.988,2,0.4,55.9986
7042,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19134,East,Technology,Copiers,599.970,5,0.4,69.9965
8123,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19134,East,Technology,Copiers,1079.976,4,0.4,125.9972
8799,First Class,Consumer,United States,Philadelphia,Pennsylvania,19134,East,Technology,Copiers,1799.970,5,0.4,239.9960
8808,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19134,East,Technology,Phones,118.650,5,0.4,19.7750
9106,Standard Class,Consumer,United States,Houston,Texas,77041,Central,Technology,Machines,287.910,3,0.4,33.5895
9516,Second Class,Consumer,United States,Bowling Green,Ohio,43402,East,Technology,Phones,26.982,3,0.4,4.0473
9617,Standard Class,Corporate,United States,Bowling Green,Ohio,43402,East,Technology,Copiers,899.982,3,0.4,74.9985
9798,Standard Class,Corporate,United States,Toledo,Ohio,43615,East,Technology,Phones,26.376,4,0.4,2.6376

total_discount_profit = 26 records

#### Q.7 Find high-profit orders where Quantity > 5 and Category == 'Technology'

In [9]:
# Step 1: Show Technology category 
tech_only = df[df['Category'] == 'Technology']

# Step 2: Total Print only Technology records 
print(f"Total Technology Records = {len(tech_only)}")

# Step 3: Result display 
tech_only

Total Technology Records = 1847

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
7,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.152,6,0.2,90.7152
11,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,911.424,4,0.2,68.3568
19,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,213.480,3,0.2,16.0110
26,Second Class,Consumer,United States,Los Angeles,California,90049,West,Technology,Accessories,90.570,3,0.0,11.7741
35,First Class,Corporate,United States,Richardson,Texas,75080,Central,Technology,Phones,1097.544,7,0.2,123.4737
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9983,Standard Class,Consumer,United States,Grand Rapids,Michigan,49505,Central,Technology,Phones,97.980,2,0.0,27.4344
9986,Standard Class,Consumer,United States,Los Angeles,California,90008,West,Technology,Accessories,36.240,1,0.0,15.2208
9987,Standard Class,Corporate,United States,Athens,Georgia,30605,South,Technology,Accessories,79.990,1,0.0,28.7964
9988,Standard Class,Corporate,United States,Athens,Georgia,30605,South,Technology,Phones,206.100,5,0.0,55.6470
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.576,2,0.2,19.3932

In [11]:
# Step 1: Data Filter
high_profit_tech = df[(df['Quantity'] > 5) & (df['Category'] == 'Technology') & (df['Profit'] > 100)]


# Step 2: Display 
displayhigh_profit_tech

# Step 3: Total count print 
print(f"Total High-Profit Tech Orders = {len(high_profit_tech)}")

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
35,First Class,Corporate,United States,Richardson,Texas,75080,Central,Technology,Phones,1097.544,7,0.2,123.4737
147,Standard Class,Corporate,United States,Franklin,Wisconsin,53132,Central,Technology,Phones,384.450,11,0.0,103.8015
159,Standard Class,Consumer,United States,Edmond,Oklahoma,73034,Central,Technology,Phones,944.930,7,0.0,236.2325
251,Standard Class,Consumer,United States,San Diego,California,92037,West,Technology,Accessories,3347.370,13,0.0,636.0003
281,Second Class,Consumer,United States,Houston,Texas,77070,Central,Technology,Phones,1114.400,7,0.2,376.1100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9398,First Class,Consumer,United States,New York City,New York,10011,East,Technology,Phones,1349.910,9,0.0,661.4559
9407,Second Class,Consumer,United States,New York City,New York,10035,East,Technology,Accessories,1071.000,9,0.0,171.3600
9504,Standard Class,Corporate,United States,New York City,New York,10009,East,Technology,Phones,1091.930,7,0.0,272.9825
9660,Standard Class,Home Office,United States,Santa Barbara,California,93101,West,Technology,Phones,3023.928,9,0.2,226.7946
9833,Standard Class,Corporate,United States,Springfield,Ohio,45503,East,Technology,Accessories,895.944,7,0.2,190.3881

Total High-Profit Tech Orders = 102

#### Q.8 Select rows 0–4 and columns 'Ship Mode', 'Segment', 'Sales' by position using iloc?

In [12]:
# Step 1: Rows (0 to 4) and Columns (0, 1 and 9) using iloc
SSS = df.iloc[0:5, [0, 1, 9]]

# Step 2: Result display 
SSS

        Ship Mode    Segment     Sales
0    Second Class   Consumer  261.9600
1    Second Class   Consumer  731.9400
2    Second Class  Corporate   14.6200
3  Standard Class   Consumer  957.5775
4  Standard Class   Consumer   22.3680

#### Q.9 Show Home Office segment orders with Sales > 1000 and Quantity > 3.?

In [13]:
# Step 1: filter home ofice, segment, quantity
h_s_q = df[(df['Segment'] == 'Home Office') & (df['Sales'] > 1000) & (df['Quantity'] > 3)]

# Step 2: Table display 
display(h_s_q)

# Step 3: Total count print 
print(f"Total Home Office Orders (Sales > 1000 & Qty > 3) = {len(h_s_q)}")

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
244,Second Class,Home Office,United States,Lakeville,Minnesota,55044,Central,Furniture,Chairs,2001.860,7,0.0,580.5394
247,Second Class,Home Office,United States,Lakeville,Minnesota,55044,Central,Office Supplies,Appliances,1503.250,5,0.0,496.0725
353,First Class,Home Office,United States,New York City,New York,10009,East,Office Supplies,Binders,4355.168,4,0.2,1415.4296
463,Standard Class,Home Office,United States,Phoenix,Arizona,85023,West,Furniture,Tables,1272.630,6,0.5,-814.4832
515,Standard Class,Home Office,United States,Great Falls,Montana,59405,West,Technology,Copiers,2999.950,5,0.0,1379.9770
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8890,Second Class,Home Office,United States,Columbia,Missouri,65203,Central,Office Supplies,Appliances,1927.590,7,0.0,751.7601
8892,Standard Class,Home Office,United States,San Diego,California,92037,West,Furniture,Chairs,2676.672,9,0.2,267.6672
9056,First Class,Home Office,United States,New York City,New York,10011,East,Furniture,Chairs,2621.322,11,0.1,553.3902
9660,Standard Class,Home Office,United States,Santa Barbara,California,93101,West,Technology,Phones,3023.928,9,0.2,226.7946
9673,Standard Class,Home Office,United States,Philadelphia,Pennsylvania,19143,East,Technology,Phones,1499.970,5,0.4,-374.9925

Total Home Office Orders (Sales > 1000 & Qty > 3) = 73

#### Q.10 10- Find orders where Profit Margin > 0.3
#### Profit Margin = (Profit/Sales)

In [14]:
# Step 1: Create New Column with formula "Profit Margin"
df['Profit Margin'] = df['Profit'] / df['Sales']

# Step 2: New column (Profit Margin) par > 0.3 
p_m = df[df['Profit Margin'] > 0.3]

# Step 3: Table display
display(p_m)

# Step 4: Total count print
print(f"Total Orders with Profit Margin > 0.3 = {len(p_m)}")

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit Margin
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.620,2,0.0,6.8714,0.4700
8,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,18.504,3,0.2,5.7825,0.3125
12,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,15.552,3,0.2,5.4432,0.3500
13,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,407.976,3,0.2,132.5922,0.3250
20,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Binders,22.720,4,0.2,7.3840,0.3250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9982,Standard Class,Consumer,United States,Grand Rapids,Michigan,49505,Central,Office Supplies,Paper,35.560,7,0.0,16.7132,0.4700
9984,Standard Class,Consumer,United States,Long Beach,New York,11561,East,Office Supplies,Labels,31.500,10,0.0,15.1200,0.4800
9986,Standard Class,Consumer,United States,Los Angeles,California,90008,West,Technology,Accessories,36.240,1,0.0,15.2208,0.4200
9987,Standard Class,Corporate,United States,Athens,Georgia,30605,South,Technology,Accessories,79.990,1,0.0,28.7964,0.3600
9992,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.600,4,0.0,13.3200,0.4500

Total Orders with Profit Margin > 0.3 = 4145