# Assignment 11

#### Q.1 Check Duplicate Records

In [1]:
# Step 1 read import pandas and csv file
import pandas as pd

df = pd.read_csv("cars.csv")

In [2]:
df

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [3]:
# Step 2: Total duplicate rows checking
duplicate_count = df.duplicated().sum()
print("Total Duplicate Rows:", duplicate_count)

# Step 3: Duplicate display 
duplicate_rows = df[df.duplicated()]
duplicate_rows

Total Duplicate Rows: 715

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
14,BMW,1 Series,2013,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,19,3916,31500
18,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
20,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
24,Audi,100,1993,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
25,Audi,100,1993,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11481,Suzuki,X-90,1998,regular unleaded,95.0,4.0,MANUAL,four wheel drive,2.0,NaN,Compact,2dr SUV,26,22,481,2000
11603,Volvo,XC60,2017,regular unleaded,302.0,4.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Luxury,Performance",Midsize,4dr SUV,29,20,870,46350
11604,Volvo,XC60,2017,regular unleaded,240.0,4.0,AUTOMATIC,front wheel drive,4.0,"Crossover,Luxury",Midsize,4dr SUV,30,23,870,40950
11708,Suzuki,XL7,2008,regular unleaded,252.0,6.0,AUTOMATIC,all wheel drive,4.0,Crossover,Midsize,4dr SUV,22,15,481,29149
11717,Suzuki,XL7,2008,regular unleaded,252.0,6.0,AUTOMATIC,front wheel drive,4.0,Crossover,Midsize,4dr SUV,22,16,481,27499

#### Q.2 Drop Duplicate Records

In [4]:
# Step 1: Duplicate rows delete (drop) karna
df = df.drop_duplicates()

# Step 2: Verify rows aur columns 
print("Duplicates drop kay bad dataset shape:", df.shape)

# Step 3: again check duplicates data
print("Check duplicate rows:", df.duplicated().sum())

Duplicates drop kay bad dataset shape: (11199, 16)
Check duplicate rows: 0

#### Q.3 Check missing or null values

In [5]:
# Dataset missing / null values checking
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3376
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

#### Q.4 Drop missing or null values

In [6]:
# Step 1: Missing/ null values rows deleting (drop)
df = df.dropna()

# Step 2: Verify null values drop or not
print("\nMissing values drop k baad dataset ka shape:", df.shape)
print("\nRemaing null values:")
print(df.isnull().sum())

Missing values drop k baad dataset ka shape: (7735, 16)

Remaing null values:
Make                 0
Model                0
Year                 0
Engine Fuel Type     0
Engine HP            0
Engine Cylinders     0
Transmission Type    0
Driven_Wheels        0
Number of Doors      0
Market Category      0
Vehicle Size         0
Vehicle Style        0
highway MPG          0
city mpg             0
Popularity           0
MSRP                 0
dtype: int64

#### Q.5 Show top 10 average MSRP (Price) per car brand (rounded figure)?

In [7]:
# Step 1: Every car brand (Make) average MSRP calculate and round 
top_10_brands = (
    df.groupby("Make")["MSRP"]
    .mean()
    .round()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

# Step 2: Result display
top_10_brands

           Make       MSRP
0       Bugatti  1757224.0
1       Maybach   546222.0
2   Rolls-Royce   351131.0
3   Lamborghini   331567.0
4       Bentley   247169.0
5       McLaren   239805.0
6       Ferrari   237384.0
7        Spyker   214990.0
8  Aston Martin   198123.0
9      Maserati   113684.0

#### Q.6 Show the average MSRP (price) per years (rounded figure)?

In [8]:
# Step 1: Every (Year) average MSRP calculate and round 
avg_msrp_per_year = df.groupby("Year")["MSRP"].mean().round().reset_index()

# Step 2: Result display 
avg_msrp_per_year

    Year     MSRP
0   1990   2073.0
1   1991   2223.0
2   1992   2192.0
3   1993   2401.0
4   1994   2726.0
5   1995   3270.0
6   1996   3140.0
7   1997   4524.0
8   1998   4434.0
9   1999   3612.0
10  2000   3913.0
11  2001  73833.0
12  2002  55704.0
13  2003  68312.0
14  2004  55908.0
15  2005  53724.0
16  2006  39001.0
17  2007  41173.0
18  2008  80462.0
19  2009  59193.0
20  2010  60152.0
21  2011  65663.0
22  2012  71837.0
23  2013  55201.0
24  2014  71196.0
25  2015  52613.0
26  2016  52580.0
27  2017  45333.0

#### Q.7 Show average Engine HP (power) rounded figure and MPG (efficiency) rounded figure per year?
#### Hint: Average of (city mpg + highway MPG)

In [9]:
# Step 1: Every car combined Average MPG (efficiency) 
df["MPG"] = (df["city mpg"] + df["highway MPG"]) / 2

# Step 2: Every (Year) Engine HP and MPG average nikalna aur round karna
avg_hp_mpg_year = (
    df.groupby("Year")[["Engine HP", "MPG"]].mean().round().reset_index()
)

# Step 3: Result table display
avg_hp_mpg_year

    Year  Engine HP   MPG
0   1990      154.0  21.0
1   1991      163.0  21.0
2   1992      155.0  22.0
3   1993      174.0  21.0
4   1994      167.0  21.0
5   1995      203.0  20.0
6   1996      201.0  21.0
7   1997      200.0  21.0
8   1998      224.0  20.0
9   1999      199.0  21.0
10  2000      202.0  21.0
11  2001      243.0  20.0
12  2002      244.0  19.0
13  2003      258.0  19.0
14  2004      260.0  19.0
15  2005      255.0  20.0
16  2006      248.0  20.0
17  2007      274.0  18.0
18  2008      298.0  19.0
19  2009      268.0  20.0
20  2010      269.0  20.0
21  2011      280.0  22.0
22  2012      293.0  22.0
23  2013      290.0  23.0
24  2014      311.0  23.0
25  2015      288.0  24.0
26  2016      290.0  24.0
27  2017      285.0  25.0

#### Q.8 What percentage of cars are Compact, Midsize, or Large?¶

In [10]:
# Step 1: Vehicle percentage 
vehicle_size_pct = (df["Vehicle Size"].value_counts(normalize=True) * 100).round(2).reset_index()

# Step 2: Columns Names Set
vehicle_size_pct.columns = ["Vehicle Size", "Percentage (%)"]

# Step 3: Result display 
vehicle_size_pct

  Vehicle Size  Percentage (%)
0      Midsize           39.34
1      Compact           36.81
2        Large           23.85

#### Q.9 Which vehicle styles are the most sold (most common) in the dataset?

In [11]:
# Step 1: Vehicle Style column count set
vehicle_styles = df["Vehicle Style"].value_counts().reset_index()

# Step 2: Columns headings 
vehicle_styles.columns = ["Vehicle Style", "Count"]

# Step 3: Top most common vehicle styles display
vehicle_styles.head(10)

         Vehicle Style  Count
0              4dr SUV   2053
1                Sedan   1801
2                Coupe    922
3          Convertible    645
4        4dr Hatchback    639
5        2dr Hatchback    409
6                Wagon    349
7      Crew Cab Pickup    334
8  Extended Cab Pickup    187
9   Regular Cab Pickup    176

#### Q.10 Which car brands have the most vehicles priced at $40,000 or more and with a popularity score of at least 1000?

In [12]:
# Step 1: Filter condition (MSRP >= 40,000 aur Popularity >= 1000)
filtered_cars = df[(df["MSRP"] >= 40000) & (df["Popularity"] >= 1000)]

# Step 2: Car brands (Make) count and table formating
popular_expensive_brands = (
    filtered_cars["Make"].value_counts().reset_index()
)
popular_expensive_brands.columns = ["Make", "Count"]

# Step 3: Top brands display 
popular_expensive_brands.head(10)

          Make  Count
0     Cadillac    354
1          BMW    269
2         Audi    224
3    Chevrolet    171
4      Porsche    123
5         Ford    105
6       Nissan     69
7      Ferrari     68
8  Lamborghini     52
9       Toyota     50