# Assignment 15 Solve all Questions

In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
conn = sql.connect('factbook.db')
conn

In [3]:
def sql_query(query):
    return pd.read_sql_query(query, conn)

In [ ]:
# Q.1 List all cities where the area is greater than 5000, along with their population.

In [24]:
q = '''
    select cn.name city_name, cn.population city_population, ca.area country_area
    from cities cn
    inner join facts ca
    on cn.facts_id = ca.id
    where ca.area > 5000
'''
sql_query(q)

     city_name  city_population  country_area
0    Abu Dhabi           942000         83600
1        Dubai          1978000         83600
2      Sharjah           983000         83600
3        Kabul          3097000        652230
4      Algiers          2916000       2381741
..         ...              ...           ...
349    Mbabane            66000         17364
350      Sanaa          2419000        527968
351       Aden           784000        527968
352     Lusaka          1802000        752618
353     Harare          1542000        390757

[354 rows x 3 columns]

In [ ]:
# Q.2 List the names of capital cities where the death rate is greater than 2% and the birth rate is less than 20%

In [9]:
q = '''
    select cc.name capital_city, db.death_rate, db.birth_rate
    from cities cc
    inner join facts db
    on cc.facts_id = db.id
    where cc.capital == 1 and db.death_rate > 2 and db.birth_rate < 20
'''
sql_query(q)

         capital_city  death_rate  birth_rate
0          Oranjestad        8.18       12.56
1        Saint John'S        5.69       15.85
2                Baku        7.07       16.64
3              Tirana        6.58       12.92
4             Yerevan        9.34       13.61
..                ...         ...         ...
123         Road Town        4.99       10.91
124             Hanoi        5.93       15.96
125  Charlotte Amalie        8.54       10.31
126          Windhoek       13.91       19.80
127          Mata-Utu        5.06       13.45

[128 rows x 3 columns]

In [ ]:
# Q.3 List the cities with a population growth rate between 1% and 5%, sorted in desc by population growth.

In [11]:
q = '''
    select cn.name city_name, pg.population_growth
    from cities cn
    inner join facts pg
    on cn.facts_id = pg.id
    where pg.population_growth between 1 and 5
    order by pg.population_growth desc
'''
sql_query(q)

     city_name  population_growth
0         Juba               4.02
1     Lilongwe               3.32
2    Bujumbura               3.28
3       Niamey               3.25
4      Kampala               3.24
..         ...                ...
210        Fes               1.00
211  Marrakech               1.00
212    Tangier               1.00
213     Agadir               1.00
214    Managua               1.00

[215 rows x 2 columns]

In [ ]:
# Q.4 Find countries that start with 'A' and do not have any cities listed in the cities table. 
# The query should return the country name and city name. Using left join

In [13]:
q = '''
    select cty.name country_name, cn.name city_name
    from facts cty
    left join cities cn
    on cty.id = cn.facts_id
    where cty.name like 'A%' and cn.name is null
'''
sql_query(q)

                  country_name city_name
0  Ashmore and Cartier Islands      None
1                     Akrotiri      None
2                   Antarctica      None
3                 Arctic Ocean      None
4               Atlantic Ocean      None

In [ ]:
# Q.5 List all capital cities and their corresponding death rate using a LEFT JOIN.

In [18]:
q = '''
    select cc.name capital_city, dr.death_rate
    from cities cc
    left join facts dr
    on cc.facts_id = dr.id
    where cc.capital == 1
'''
sql_query(q)

     capital_city  death_rate
0      Oranjestad        8.18
1    Saint John'S        5.69
2       Abu Dhabi        1.97
3           Kabul       13.89
4         Algiers        4.31
..            ...         ...
203          Apia        5.32
204       Mbabane       13.56
205         Sanaa        6.28
206        Lusaka       12.67
207        Harare       10.13

[208 rows x 2 columns]