In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
conn = sql.connect('database.sqlite')
conn

In [10]:
q = "SELECT * FROM Salaries"
sql_query(q)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,567595.43,567595.43,2011,,San Francisco,
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,,538909.28,538909.28,2011,,San Francisco,
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [3]:
def sql_query(q):
    return pd.read_sql_query(q, conn)

In [8]:
# Solve Question 1

q1 = """ Select Jobtitle, AVG(TotalPaybenefits)
        as AVG_Total_PAY_BENEFITS from salaries
    where JobTitle not in ('Not Provided', 'Not provided')
    group by JobTitle

"""

sql_query(q1)

                                            JobTitle  AVG_Total_PAY_BENEFITS
0                                      ACCOUNT CLERK            44035.664337
1                                         ACCOUNTANT            47429.268000
2                                  ACCOUNTANT INTERN            29031.742917
3                        ACPO,JuvP, Juv Prob (SFERS)            80266.370000
4                                      ACUPUNCTURIST            67594.400000
...                                              ...                     ...
2153                           X-RAY LABORATORY AIDE            52705.880385
2154                           X-Ray Laboratory Aide            69521.123200
2155  YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS            53632.870000
2156                              Youth Comm Advisor            60118.550000
2157                                     ZOO CURATOR            66686.560000

[2158 rows x 2 columns]

In [12]:
# Solve Question 2

q2 = """ SELECT JobTitle, OvertimePay FROM Salaries
            WHERE OvertimePay > 50000
            AND OvertimePay != 'Not Provided'
            
"""

sql_query(q2)

                                  JobTitle  OvertimePay
0          CAPTAIN III (POLICE DEPARTMENT)    245131.88
1          CAPTAIN III (POLICE DEPARTMENT)    106088.18
2     WIRE ROPE CABLE MAINTENANCE MECHANIC     56120.71
3       BATTALION CHIEF, (FIRE DEPARTMENT)     89062.90
4       BATTALION CHIEF, (FIRE DEPARTMENT)     86362.68
...                                    ...          ...
2160                      Transit Operator     51625.42
2161                      Transit Operator     52550.53
2162              Track Maintenance Worker     50265.23
2163             Diagnostic Imaging Tech I     74935.96
2164               Parking Control Officer     54738.36

[2165 rows x 2 columns]

In [13]:
# Solve Question 3

q3 = """ SELECT COUNT(DISTINCT EmployeeName) AS Total_Unique_Employees FROM Salaries
            WHERE EmployeeName NOT IN ('Not Provided', 'Not provided')
"""

sql_query(q3)

   Total_Unique_Employees
0                  110809

In [18]:
# Solve Question 4

q4 = """ SELECT EmployeeName, TotalPayBenefits FROM Salaries
            ORDER BY TotalPayBenefits DESC LIMIT 10
            
"""

sql_query(q4)

           EmployeeName  TotalPayBenefits
0        NATHANIEL FORD         567595.43
1          GARY JIMENEZ         538909.28
2           David Shinn         510732.68
3            Amy P Hart         479652.21
4  William J Coaker Jr.         436224.36
5        Gregory P Suhr         425815.28
6  Joanne M Hayes-White         422353.40
7        Gregory P Suhr         418019.22
8  Joanne M Hayes-White         417435.10
9       Ellen G Moffatt         415767.94

In [15]:
# Solve Question 4 Other Example with complete Database

q4 = """ SELECT * FROM Salaries
            ORDER BY TotalPayBenefits DESC LIMIT 10
            
"""

sql_query(q4)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,,567595.43,567595.43,2011,,San Francisco,
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,,538909.28,538909.28,2011,,San Francisco,
2,110532,David Shinn,Deputy Chief 3,129150.01,0.00,342802.63,38780.04,471952.64,510732.68,2014,,San Francisco,PT
3,110533,Amy P Hart,Asst Med Examiner,318835.49,10712.95,60563.54,89540.23,390111.98,479652.21,2014,,San Francisco,FT
4,110534,William J Coaker Jr.,Chief Investment Officer,257340.00,0.00,82313.70,96570.66,339653.70,436224.36,2014,,San Francisco,PT
5,72926,Gregory P Suhr,Chief of Police,319275.01,0.00,20007.06,86533.21,339282.07,425815.28,2013,,San Francisco,
6,72927,Joanne M Hayes-White,"Chief, Fire Department",313686.01,0.00,23236.00,85431.39,336922.01,422353.40,2013,,San Francisco,
7,110535,Gregory P Suhr,Chief of Police,307450.04,0.00,19266.72,91302.46,326716.76,418019.22,2014,,San Francisco,FT
8,110536,Joanne M Hayes-White,"Chief, Fire Department",302068.00,0.00,24165.44,91201.66,326233.44,417435.10,2014,,San Francisco,FT
9,110537,Ellen G Moffatt,Asst Med Examiner,270222.04,6009.22,67956.20,71580.48,344187.46,415767.94,2014,,San Francisco,FT

In [19]:
q5 = """ SELECT EmployeeName, TotalPayBenefits  FROM Salaries 
            ORDER BY TotalPayBenefits DESC
"""

sql_query(q5)

                EmployeeName  TotalPayBenefits
0             NATHANIEL FORD         567595.43
1               GARY JIMENEZ         538909.28
2                David Shinn         510732.68
3                 Amy P Hart         479652.21
4       William J Coaker Jr.         436224.36
...                      ...               ...
148649          Not provided              0.00
148650      Timothy E Gibson             -2.73
148651        Mark E Laherty             -8.20
148652         David P Kucia            -33.89
148653             Joe Lopez           -618.13

[148654 rows x 2 columns]